class QwirkleMetric {
    constructor(log) {
        this.timeLog = log[0]
        this.timeAction = log [1]
        this.version = log [2]
        this.userId = log [3]
        this.username = log [4]
        this.deviceId = log [5]
        this.connectionType = log [6]
        this.deviceHostId = log [7]
        this.level = log [8]
        this.vip = log [9]
        this.platform = log [10]
        this.locate = log [11]
        this.socialType = log [12]
        this.isNew = log [13]
        this.default1 = log [14]
        this.default2 = log [15]
        this.default3 = log [16]
        this.default4 = log [17]
        this.default5 = log [18]
        this.default6 = log [19]
        this.default7 = log [20]
        this.timeCreate = log [21]
        this.group = log [22]
        this.action = log [23]
        this.gold = log [24]
        this.coin = log [25]
        this.goldChange = log [26]
        this.coinChange = log [27]
        this.extra1 = log [28]
        this.extra2 = log [29]
        this.extra3 = log [30]
        this.extra4 = log [31]
        this.extra5 = log [32]
        this.extra6 = log [33]
        this.extra7 = log [34]
        this.extra8 = log [35]
        this.extra9 = log [36]
        this.extra10 = log [37]
        this.extra11 = log [38]
        this.extra12 = log [39]
        this.extra13 = log [40]
        this.extra14 = log [41]
        this.extra15 = log [42]
    }
}

module.exports = {
    QwirkleMetric
};